### ISSUE TITLE
Problème de génération du SVG avec les paramètres par défaut pour les dépendances fonctionnelles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [laowantong/mocodo#10]
```
Bonjour,
 
Si l'on n'ajoute pas l'option "--df=", le fichier sandbox-svg.py généré 
contient 'text': DF, ce qui génère des erreurs "NameError: name 'DF' is not 
defined" (problème de valeur par défaut ?)

L'ajout du paramètre "--df=DF suffit à contourner ce problème.

Version 1.6.1 sous Windows 8.1
```

Original issue reported on code.google.com by `zekrap` on 20 Dec 2013 at 1:12

**Comment by laowantong** [comment]
Désolé, je n'ai pris connaissance des bogues signalées sur Google Code qu'aujourd'hui en les retrouvant sur GitHub où je viens de faire migrer le projet. Je n'avais pas connaissance de ce problème. J'ai complètement réécrit la gestion des paramètres pour la version 2, donc par défaut je suppose qu'il est réglé. N'hésitez pas à me relancer pour rouvrir l'issue le cas échéant.
