### ISSUE TITLE
Générateur de MCD - asso réflexive

### ISSUE THREAD

**Issue by fduchatea** [laowantong/mocodo#105]
En générant un MCD (avec l'option `grow_from_scratch`), Mocodo génère une asso nommée Réflexive, qui pourtant n'en est pas une (Réflexive_18 dans le code).

```
Réflexive 15_, 1N Entité 8_, 1N Entité 8_
Réflexive 14_, 1N Entité 8_, 01 Entité 8_
Entité 12_: id 12 1 [INTEGER], at 12 2 [INTEGER]
Réflexive 18_, 0N Entité 16_, 01 Entité 6_
Entité 16_: id 16 1 [INTEGER], at 16 2 [INTEGER]

Binaire 11_, 0N Entité 10_, 1N Entité 8_
Entité 8_: id 8 1 [INTEGER], at 8 2 [INTEGER]
Ternaire 13_, 0N Entité 12_, 1N Entité 6_, 1N Entité 8_
Entité 6_: id 6 1 [INTEGER], at 6 2 [INTEGER], at 6 3 [INTEGER]
Binaire 17_, 1N Entité 16_, 0N Entité 6_: at 17 1 [INTEGER]

Entité 10_: id 10 1 [INTEGER], at 10 2 [INTEGER], at 10 3 [INTEGER]
Binaire 9_, 1N Entité 8_, 01 Entité 4_: at 9 1 [INTEGER]
Entité 4_: id 4 1 [INTEGER], at 4 2 [INTEGER], at 4 3 [INTEGER]
Binaire 7_, 0N Entité 6_, 0N Entité 4_
Entité 1_: id 1 1 [INTEGER], at 1 2 [INTEGER], at 1 3 [INTEGER]

:
:
Binaire 5_, 11 Entité 4_, 01 Entité 2_
Entité 2_: id 2 1 [INTEGER], at 2 2 [INTEGER]
Binaire 3_, 1N Entité 2_, 1N Entité 1_%  
```

Le pdf est le suivant (l'asso non réflexive est en haut à droite) :

<img width="939" alt="Capture d’écran 2023-12-04 à 09 42 36" src="https://github.com/laowantong/mocodo/assets/54939958/5166e6ce-91d9-41f4-909a-0a4ac8d8b98d">

Il y a aussi le cas inverse qui se produit : une Réflexive qui est nommée Binaire K.
Ce n'est pas un réel problème (peu d'impact, sauf si on utilise les libellés pour apprendre à repérer les différents types d'assos par ex).

**Comment by laowantong** [comment]
En effet, étrange, je regarderai ça. Merci.

**Comment by laowantong** [comment]
Je verrai si je peux reproduire. Tu n'as pas fait ça avec un `--seed` fixé ?
