### ISSUE TITLE
Caractère # dans la sortie Latex

### ISSUE THREAD

**Issue by fduchatea** [laowantong/mocodo#106]
Dans la sortie Latex, un '#' apparait devant le nom des attributs (clés étrangères), ce qui fait échouer la compilation Latex (il faudrait '\#', mais a-priori c'est la macro \foreign qui est en charge de mettre le dièse). Il faut donc supprimer le '#' de la sortie.

```
\item \relat{V} (\prim{imp}, \foreign{\prim{#lib}})
```

Toujours en version Mocodo 4.0.5, mais ça a peut-être été corrigé dans une version plus récente.

**Comment by laowantong** [comment]
Ça ne marcherait pas simplement en l'échappant ?

**Comment by laowantong** [comment]
Ok, il doit y avoir une redondance effectivement.

Le gabarit `latex-b` dérive de `latex-bc` qui définit ce qu'il faut.

**Comment by fduchatea** [comment]
J'ai trouvé la définition des macros : elle est dans [latex-bc](https://github.com/laowantong/mocodo/blob/master/mocodo/resources/relation_templates/latex-bc.yaml).
Peut-être que mocodo online devrait produire ce gabarit latex-bc au lieu de latex ?

**Comment by laowantong** [comment]
Oui, pourquoi pas ? Il faut que je vois la cohérence avec les autres options.

**Comment by fduchatea** [comment]
La sortie Latex du schéma relationnel sous forme de liste n'est pas très esthétique (avec les puces devant chaque relation). Je vais voir pour modifier un gabarit.

**Comment by fduchatea** [comment]
Voici un gabarit (testé sous mocodo 4.0.5). Pas de PR car je n'ai pas encore le dépôt Mocodo en local...
En plus il faut probablement le renommer.

[latex-fd.yaml.zip](https://github.com/laowantong/mocodo/files/13566005/latex-fd.yaml.zip)

Voici un exemple de sortie Latex (liste sans puce, plus compacte) : 

<img width="427" alt="Capture d’écran 2023-12-05 à 18 58 40" src="https://github.com/laowantong/mocodo/assets/54939958/9ac3f776-573a-4753-b508-3217665475e9">

Sinon, après avoir placé le nouveau gabarit dans `resources/relation_templates/`, on ne peut pas l'utiliser avec `-t nouveau_gab` : il faut utiliser `-t relation:nouveau_gab`. Peut-être mieux l'expliquer dans la doc (qui insiste surtout sur le chemin complet vers le gabarit).

Autre souci avec la sortie Latex : les noms de tables / attributs contenant des '_' doivent être échappés avec un backslash (cas fréquent si on génère un MCD ou si on utilise la notation snakecase).

**Comment by laowantong** [comment]
- Les gabarits `latex-c` et `latex-bc` sont corrigés.
- Mocodo online invoque maintenant `latex:b` ou `latex:bc` (donc avec _boilerplate_).
- Dans la doc :
  > **NB.** Les gabarits définis par l'utilisateur n'ont **pas** vocation à être placés dans le répertoire `relation_templates` de la distribution. Votre nouveau gabarit `new_sql` ne peut donc pas être invoqué aussi simplement que les gabarits officiels (i.e., avec `-t new_sql`). Si vous faites une modification ou un ajout que vous voulez voir inclus dans la distribution, n'hésitez pas à faire une PR.
- Je ne pense pas retenir ta proposition de redéfinition de liste, qui me paraît moins claire quand une relation compte plusieurs lignes.

**Comment by fduchatea** [comment]
Ok pour les corrections, je regarderai plus tard.

Si ça intéresse d'autres personnes, voici comment retirer les puces quand on inclut le code Latex généré par Mocodo :
```
{%
\renewcommand\labelitemi{}% remove bullets
\input{dataset.tex}
}
```

Pour les gabarits : je ne les mets pas directement dans le répertoire `relation_templates`. Ils sont dans un répertoire perso, et un script les copie dans `relation_templates`.

**Comment by laowantong** [comment]
Si tu tiens à copier ton gabarit dans le dossier officiel, ton script doit aussi lancer `dev/update_transfo_metadata.py`.
