### ISSUE TITLE
Rôles (partiellement) ignorés dans les agrégations lors du passage au SR

### ISSUE THREAD

**Issue by Epithumia** [laowantong/mocodo#110]
Quand une entité fille est utilisée pour des associations, elle utilise mal les rôles définis en cas d'associations parallèles lorsqu'on passe au SR : le premier rôle est utilisé comme rôle pour toutes les associations.

Sans agrégation, ça fonctionne comme prévu, par exemple : 
```
:
EQUIPE: idEquipe,nomEquipe
:

accueille, 11 MATCH, 0N [-hote] EQUIPE
:
recoit, 11 MATCH, 0N [-visiteur] EQUIPE

:
MATCH: idMatch
:
```

devient bien 
```
%%mocodo
:
Equipe: IdEquipe, NomEquipe
:



:
Match: IdMatch, #hote > Equipe > IdEquipe, #visiteur > Equipe > IdEquipe
:
```

En revanche, si MATCH est une entité fille, ça rate :

```
:
EQUIPE: idEquipe,nomEquipe
:

accueille, 11 MATCH, 0N [-hote] EQUIPE
:
recoit, 11 MATCH, 0N [-visiteur] EQUIPE

:
MATCH: idMatch
:

/XT\ RENCONTRE <- MATCH: typeRencontre

RENCONTRE: idRencontre
```

devient
```
%%mocodo
:
Equipe: IdEquipe, NomEquipe
:





:
Rencontre: IdRencontre, TypeRencontre, IdMatch, #hote 1 > Equipe > IdEquipe, #hote 2 > Equipe > IdEquipe
:
```

Testé en ligne et sur la version 4.2.2 CLI.

**Comment by laowantong** [comment]
Pour confirmer, ça donne actuellement ça :

- **EQUIPE** (<ins>idEquipe</ins>, nomEquipe)
- **RENCONTRE** (<ins>idRencontre</ins>, typeRencontre, idMatch, _#hote 1_, _#hote 2_)

Mais vous attendez ça ?

- **EQUIPE** (<ins>idEquipe</ins>, nomEquipe)
- **RENCONTRE** (<ins>idRencontre</ins>, typeRencontre, idMatch, _#hote_, _#visiteur_)

**Comment by Epithumia** [comment]
C'est bien ça (comme quand il n'y a pas de spécialisation).

**Comment by laowantong** [comment]
Ça devrait être [bon](https://www.mocodo.net/?mcd=eNo73FlYmlmQaqWQmaJweCWYrZOXnwtjczkmJ5emZubkpOooGBoq-CaWJGfoKBj4KUTrZhzeUpIaq3AYYgAXV1Dq4eX5mSUY6soyizNLUkuLEErBsmAbc0EskNa85Py8kiKIM4pgPC79iJAYBbikgo2uAlRrSWVBKlycCwDaGkaK).
