### ISSUE TITLE
Documentation pas à jour (utilisation par importation)

### ISSUE THREAD

**Issue by Epithumia** [laowantong/mocodo#111]
La documentation (https://rawgit.com/laowantong/mocodo/master/doc/fr_refman.html#Utilisation-par-importation) donne comme syntaxe `from mocodo import mocodo`, mais cela ne fonctionne pas dans la version 4.2.4. 

Sauf erreur de ma part, c'est maintenant `from mocodo.api import mocodo` qui assure cette fonctionnalité.

**Comment by laowantong** [comment]
Merci !

**Comment by Epithumia** [comment]
J'ai l'impression que quelque chose a raté lors de la génération de la doc. La table des matières n'est plus sur le côté, mais dans la toute première cellule et occupe toute la largeur de la page.

**Comment by laowantong** [comment]
Oui, j'ai vu ça. C'est probablement dû à la mise à jour de `nbconvert`.
