### ISSUE TITLE
Les commandes Mocodo d'exemple ne fonctionnent pas

### ISSUE THREAD

**Issue by Taratata37** [laowantong/mocodo#121]
Les commandes Mocodo d'exemple ne fonctionnent pas. Ou retournent un message inintelligible.

1. Je me place dans un répertoire vide
2. Je lance la commande ""mocodo", cela fonctionnne
3. J'essaie une commande plus élaborée au hasard de la documentaiton ça plante:

`mocodo -i sandbox --select mcd -t flip:h`
Voilà la sortie console
```usage:
 mocodo [--language CODE] [--params_path PATH] [--input PATH] [--help]
              [--version] [--restore] [--df STR] [--card_format [STR]]
              [--strengthen_card [STR]] [--flex FLOAT] [--colors STEM_OR_PATH]
              [--shapes STEM_OR_PATH] [--scale RATE] [--adjust_width RATE]
              [--hide_notes] [--detect_overlaps]
              [--relations [STEM_OR_PATH ...]]
              [--disambiguation {numbers_only,notes}] [--title STR]
              [--guess_title] [--output_dir PATH] [--encodings [STR ...]]
              [--png] [--pdf] [--print_params] [--reuse_geo]
              [--uid_suffix INT] [--arrange [{bb,ga,lp}]] [--timeout SECONDS]
              [--verbose] [--fit [INT]] [--flip {h,v,d}] [--obfuscate [PATH]]
              [--obfuscation_min_distance NAT*] [--seed FLOAT]
              [--call_limit NAT*] [--min_objective NAT*]
              [--max_objective NAT*] [--organic] [--population_size NAT*]
              [--crossover_rate RATE] [--mutation_rate RATE]
              [--sample_size NAT*] [--max_generations NAT*] [--plateau NAT*]
              [--mld] [--no_mcd] [--replace]
mocodo: error: unrecognized arguments: -i sandbox --select mcd -t flip:h

```

**Comment by laowantong** [comment]
Je n’ai pas accès à mon ordinateur en ce moment, mais je n’ai pas rencontré ni entendu parler de ce type de problème. Le message « inintelligible » est la liste des arguments produite quand une commande n’arrive pas à interpréter ceux qui sont fournis. Essayez déjà simplement :mocodosans arguments. Si ça marche, tapez à la main une commande de la doc (de préférence une qui n’a pas besoin d’input comme celle que vous avez choisie) pour vérifier qu’il n’y a pas un problème de copier-coller de caractères invisibles. Le 16 nov. 2024 à 21:05, Julien ***@***.***> a écrit :﻿
Les commandes Mocodo d'exemple ne fonctionnnent pas. Ou retournent un message inintelligible.

Je me place dans un répertoire vide
Je lance la commande ""mocodo", cela fonctionnne
J'essaie une commande plus élaborée au hasard de la documentaiton ça plante:

mocodo -i sandbox --select mcd -t flip:h
Voilà la sortie console
 mocodo [--language CODE] [--params_path PATH] [--input PATH] [--help]
              [--version] [--restore] [--df STR] [--card_format [STR]]
              [--strengthen_card [STR]] [--flex FLOAT] [--colors STEM_OR_PATH]
              [--shapes STEM_OR_PATH] [--scale RATE] [--adjust_width RATE]
              [--hide_notes] [--detect_overlaps]
              [--relations [STEM_OR_PATH ...]]
              [--disambiguation {numbers_only,notes}] [--title STR]
              [--guess_title] [--output_dir PATH] [--encodings [STR ...]]
              [--png] [--pdf] [--print_params] [--reuse_geo]
              [--uid_suffix INT] [--arrange [{bb,ga,lp}]] [--timeout SECONDS]
              [--verbose] [--fit [INT]] [--flip {h,v,d}] [--obfuscate [PATH]]
              [--obfuscation_min_distance NAT*] [--seed FLOAT]
              [--call_limit NAT*] [--min_objective NAT*]
              [--max_objective NAT*] [--organic] [--population_size NAT*]
              [--crossover_rate RATE] [--mutation_rate RATE]
              [--sample_size NAT*] [--max_generations NAT*] [--plateau NAT*]
              [--mld] [--no_mcd] [--replace]
mocodo: error: unrecognized arguments: -i sandbox --select mcd -t flip:h

**Comment by laowantong** [comment]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/87ec7559-20e0-48a0-bdbc-80d2892d1131">

Je ne peux pas reproduire le problème, n'hésitez pas à rouvrir cette issue s'il persiste et que vous avez des informations complémentaires.

**Comment by Taratata37** [comment]
je suis en version mocodo 3.2.0. J'ai pourtant installé mocodo avec pip

**Comment by Taratata37** [comment]
après un  `pip install mocodo --upgrade` cela fonctionne comme attendu. Je vous remercie.
