### ISSUE TITLE
[suggestion] exporter vers mcd LaTeX

### ISSUE THREAD

**Issue by JulienAMOURIQ** [laowantong/mocodo#15]
Actuellement on peut déjà exporter le MLD en LaTeX. C'est dommage qu'on ne puisse pas réaliser également l'export du MCD en LaTeX

**Comment by laowantong** [comment]
En effet. Pour ma part, je passe par une étape de conversion en PDF (déjà, ça serait bien de n'avoir pas à compter sur un outil externe pour le faire!). Pensez-vous à un package LaTeX particulier (TikZ?).

**Comment by JulienAMOURIQ** [comment]
En effet,dans le cadre d'un projet de mon école, je dois rendre un MCD et un MLD formatés avec LaTeX. Pour le MLD ça sera facile du coup ^^.  Pour le MCD, je pourrais vous envoyer mes sources LaTeX, ça pourrait vous aider...

**Comment by laowantong** [comment]
Pour le MCD, il vous suffit donc de convertir le SVG en PDF (des outils en ligne existent) et de l'inclure dans votre LaTeX avec la commande `includegraphics`.

**Comment by JulienAMOURIQ** [comment]
Hélas j'utilise pdflatex, ce qui m'interdit d'inclure des pdf

**Comment by laowantong** [comment]
C’est mignon :)
Essayez de mettre dans le préambule:
```
\usepackage{graphicx}
```

**Comment by alexandreMesle** [comment]
Je suis arrivé sur ce thread parce que je me demandais s'il existait des macros permettant directement la saisie d'un mcd dans le document latex. 
Vraisemblablement ce n'est pas le cas, alors je vais continuer à faire comme avant... 

Pour ceux qui aiment la ligne de commande et qui préfèrent scripter, vous pouvez exporter le fichier svg vers eps ainsi :
`
inkscape ./mcd.svg --export-eps=./mcd.eps
`
Ensuite vous l'incorporez à votre document latex avec
`
\includegraphics{mcd.eps}
`

Bon courage !

**Comment by laowantong** [comment]
@alexandreMesle En effet, l'idéal pour les amateurs de LaTeX serait de pouvoir faire ce genre de choses:

```
\begin{mocodo}[mcd]
	DF, 11 Élève, 1N Classe
	Classe: Num. classe, Num. salle
	Faire Cours, 1N Classe, 1N Prof: Vol. horaire
	Catégorie: Code catégorie, Nom catégorie
	
	Élève: Num. élève, Nom élève
	Noter, 1N Élève, 0N Prof, 0N Matière, 1N Date: Note
	Prof: Num. prof, Nom prof
	Relever, 0N Catégorie, 11 Prof
	
	Date: Date
	Matière: Libellé matière
	Enseigner, 11 Prof, 1N Matière
\end{mocodo}

Et que LaTeX remplace ça par un diagramme. On en est loin :(

Pour info, la ligne de commande proposée par Alexandre marche aussi pour générer du PDF pour `pdflatex`. Il suffit de remplacer `eps` par `pdf`.
