### ISSUE TITLE
[suggestion] Transtypage automatique selon le format d'export sql

### ISSUE THREAD

**Issue by JulienAMOURIQ** [laowantong/mocodo#37]
Bonjour,

Aujourd'hui Mocodo est capable à l'aide de templates json de réaliser des exports sql pour différents moteurs de bases de données. Il serait intéressant de compléter ce dispositif pour permettre à l'aide du même code source de générer indifféremment des scripts oracle, mysql, autre.. (VARCHAR qui devient STRING ; INTEGER qui devient NUMBER, ce genre de choses).

Cordialement
Julien A.

**Comment by laowantong** [comment]
À ma connaissance il n'existe pas de standard de nommage des types, donc je doute de la généralité de ce type de traitement.

Ceci dit, vous pouvez déjà très bien le faire pour vous-même en ajoutant aux gabarits existant les expressions de recherche/remplacement désirées, par exemple:

```json
  "transform_relation": [
    {
      "search": " INTEGER,\n",
      "replace": " NUMBER,\n"
    },
```
