### ISSUE TITLE
[suggestion] Gérer les aggrégations

### ISSUE THREAD

**Issue by JulienAMOURIQ** [laowantong/mocodo#38]
Bonjour,
un ctrl+f sur la doc n'a pas révélé d'agrégation. Il s'agit pourtant d'une fonctionnalité très utile pour la modélisation . cf l'image ci-dessous pour son utilité
![pseudo_entite_cif](https://cloud.githubusercontent.com/assets/14201238/20710802/7374e8c2-b63c-11e6-975a-7a3493da86b2.png)
Une telle relation se transformerait en 
vol(**id_vol**,nom_vol...)
avion(**id_avion**,...)
date(**date**)
voler(**date,id_vol**,id_avion)

Cordialement
Julien A.

**Comment by JulienAMOURIQ** [comment]
une autre notation admise est l’utilisation d'une CIF entre voler et avion (permet d'alléger le rendu - notez l'absence de cardinalités, car inutiles) :![pseudo_entite_cif](https://cloud.githubusercontent.com/assets/14201238/20834541/45a986a8-b896-11e6-9455-472bbaf25a73.png)

**Comment by laowantong** [comment]
Oui, j'ai toujours en projet d'intégrer ces extensions de Merise 2. Quand, je ne sais pas.

La première représentation poserait _a priori_ de sérieuses difficultés pour le plongement automatique. La seconde, aucune.

J'ai cependant un doute sur la suppression des cardinalités. Le (1,1) est certainement inutile (mais pas plus qu'avec une DF, où on le met cependant). Le (1,N) ne l'est pas (ça pourrait être (0,N)). Donc je laisserais ces deux cardinalités.

Il faut aussi penser à la conversion en relationnel. Ici, on obtiendrait:

    - VOLER(_date vol_, _idVol_, idAvion)

**Comment by JulienAMOURIQ** [comment]
Tout à fait. Je n'avais pas pensé à la cardinalité côté entité, belle étourderie de ma part .

**Comment by didierbroska** [comment]
Bonjour, as ton une évolution concernant le CIF sur association ? UP

**Comment by JulienAMOURIQ** [comment]
On pourrait créer une classe cif qui hériterai de la classe entity et l'utiliser au sein d'une association sans modifier tout le moteur. Qu'en dites-vous @laowantong ?
