### ISSUE TITLE
Passage au relationnel d'entités faibles, le retour

### ISSUE THREAD

**Issue by JulienAMOURIQ** [laowantong/mocodo#40]
Bonjour, 
Le code suivant ne génère pas le bon code SQL:
> TLLANGUE:id_langue,designation
> ref, 0N TLLANGUE,_11 TLCOMM
> TLCOMM:id_comm,contenu
> 
> expliquer, 0N TLCOMM, 01 TLPARAMETRE
> 
> TLPARAMETRE: id_parametre[NUMBER(10)],nom[VARCHAR2(25)],type[VARCHAR2(25)]

En effet il ajoute "id_langue" et "id_comm" dans la table TLPARAMETRE, alors que seule la clé étrangère "id_comm" devrait être effectivement ajoutée. (enfin à mon avis, je n'ai rien trouvé à ce sujet dans la littérature à ma disposition)

**Comment by laowantong** [comment]
C'est le comportement normal, à mon avis également ;)

L'identifiant faible `id_comm` ne suffit pas à identifier une occurrence de TLCOMM. Il faut le renforcer chaque fois qu'on en a besoin, notamment quand il sert de clé étrangère.

Dans la doc, vous avez [un exemple](https://rawgit.com/laowantong/mocodo/master/doc/fr_refman.html#weak_entities_relational) encore plus complexe de renforcement en cascade.

**Comment by JulienAMOURIQ** [comment]
au temps pour moi, c'est effectivement le comportement correct
