### ISSUE TITLE
FileNotFoundError sous Jupyter Notebook

### ISSUE THREAD

**Issue by laowantong** [laowantong/mocodo#44]
Après installation de la commande magique, un appel avec lecture du texte-source du MCD dans un fichier :

```
%mocodo --input mcd/foobar.mcd
```

... échoue avec l'erreur :

```
Traceback (most recent call last):
  File "[anaconda path]/bin/mocodo", line 11, in <module>
    sys.exit(main())
  File "[anaconda path]/lib/python3.6/site-packages/mocodo/__main__.py", line 64, in main
    common.dump_mld_files(relations)
  File "[anaconda path]/lib/python3.6/site-packages/mocodo/common.py", line 108, in dump_mld_files
    write_contents(path, text)
  File "[anaconda path]/lib/python3.6/site-packages/mocodo/file_helpers.py", line 12, in write_contents
    with codecs.open(filename, encoding=encoding, mode="w") as f:
  File "[anaconda path]/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'mocodo_notebook/foobar.html'
```

Il est actuellement nécessaire de lancer au préalable la commande magique sans argument `input`, par exemple :

```
%%mocodo
A: a
```

... pour que Mocodo crée son répertoire de travail (`mocodo_notebook`). Ensuite de quoi les commandes avec `input` fonctionnent normalement.

**Comment by raoulhatterer** [comment]
Le dossier mocodo_notebook est créé automatiquement, mais l'erreur suivante apparaît. 

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-37c90f43dde8> in <module>
----> 1 get_ipython().run_cell_magic('mocodo', '', 'MISSION: accomplie\n')

/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2360             with self.builtin_trap:
   2361                 args = (magic_arg_s, cell)
-> 2362                 result = fn(*args, **kwargs)
   2363             return result
   2364 

</Applications/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-126> in mocodo(self, line, cell)

/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/Applications/anaconda3/lib/python3.7/site-packages/mocodo_magic/mocodo_magic.py in mocodo(self, line, cell)
    103             pass
    104 
--> 105         if execute_command(options):
    106             if not display_diagrams():
    107                 if "--print_params" in options:

/Applications/anaconda3/lib/python3.7/site-packages/mocodo_magic/mocodo_magic.py in execute_command(options)
     44         def execute_command(options):
     45             global stdoutdata
---> 46             process = Popen(["mocodo"] + options, stdin=PIPE, stdout=PIPE, stderr=PIPE)
     47             stdoutdata, stderrdata = process.communicate()
     48             try:

/Applications/anaconda3/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

/Applications/anaconda3/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1549                         if errno_num == errno.ENOENT:
   1550                             err_msg += ': ' + repr(err_filename)
-> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
   1552                 raise child_exception_type(err_msg)
   1553 

FileNotFoundError: [Errno 2] No such file or directory: 'mocodo': 'mocodo'`

**Comment by laowantong** [comment]
Merci ! Oui, des étudiants à moi ont déjà rencontré cette erreur, sous Windows me semble-t-il. En fait, je crois que ça n'échoue que la première fois. Après ça, le dossier en question est créé. Peut-être que ça n'a pas de rapport avec `pip`. Il doit y avoir un problème dans la séquence d'opérations, par contre.
