### ISSUE TITLE
[suggestion] Type of primary key : serial

### ISSUE THREAD

**Issue by amoulin974** [laowantong/mocodo#47]
Hi,

Create request are actually writting with primary key in varchar(42) 

Perhaps they should be in serial and foreign key in bigint(20) unsigned

**Comment by laowantong** [comment]
You can / must do this explicitly, cf. https://rawgit.com/laowantong/mocodo/master/doc/fr_refman.html#sql_generation

```
CLIENT: Réf. client [bigint(20) unsigned], Nom [varchar(20)], Adresse [varchar(40)]
```

If you want to change the placeholder, you can create another JSON specification file, e.g.:

https://github.com/laowantong/mocodo/blob/2c9e68f81bb5528134fdb4ee3cb6fc8a4042c73a/mocodo/relation_templates/mysql.json#L46-L51

Currently, it is not possible to make the default placeholder depend from the nature of a field.
