### ISSUE TITLE
Impossible d'avoir le diagramme relationnel

### ISSUE THREAD

**Issue by ManonJK** [laowantong/mocodo#48]
Je n'arrive pas du tout à obtenir le diagramme relationnel en plus du mcd, et ce malgré la lecture en long en large et en travers de la documentation. J'ai essayé sur la version online et en ligne de commande, et impossible d'obtenir le diagramme relationnel (de plus, je souhaiterais l'avoir au format svg, tout comme le mcd)

**Comment by laowantong** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html
