### ISSUE TITLE
Ne supporte pas les références de fichiers en C:\Users\...

### ISSUE THREAD

**Issue by NagoDede** [laowantong/mocodo#49]
La génération de fichier SVG ne supporte pas les fichiers qui sont dans C:\Users (les fichiers contenus dans un répertoire ..\Uxxx\ devraient aussi générer l'erreur).

L'exécution du fichier xxx_svg.py par Python conduit à lire le chemin du fichier (indiqué par la ligne _"with codecs.open(r"{output_name}.svg"_), comme un string UTF-8 et donc l'interprétation de \Users comme une référence UTF-8, générant l'erreur.
Il faut corriger le fichier _mcd_to_svg.py_ afin d'indiquer que le path est une raw string.
Le code initial 
`result.append("""\nwith codecs.open("%(output_name)s.svg", "w", "utf8") as f:\n    f.write(lines)""" % params)`
devient
`result.append((_("""\nwith codecs.open(r"{output_name}.svg", "w", "utf8") as f:\n    f.write(lines)""").format(output_name=params["output_name"])))`

Peut être utiliser pathlib pour harmoniser les générations de fichier ?

**Comment by laowantong** [comment]
Et juste:

```python
result.append("""\nwith codecs.open("%(output_name)s.svg", "w", "utf8") as f:\n    f.write(lines)""" % params)
```

... en:

```python
result.append("""\nwith codecs.open(r"%(output_name)s.svg", "w", "utf8") as f:\n    f.write(lines)""" % params)
```

... ne suffirait pas ?

C'est vrai qu'aujourd'hui je n'utilise plus que pathlib. De façon générale Mocodo aurait besoin d'une sérieuse modernisation, et donc d'un gros investissement en temps... que je ne me vois pas réussir à dégager dans un avenir proche...

**Comment by NagoDede** [comment]
Si, ça peut, tant que ça fonctionne... 
Je suis pas du tout Python (j'ai vraiment du mal à accrocher aux concepts même). Du coup, je ne vais pas me proposer pour reprendre. Mais l'outil à l'avantage de faire des schémas directement exportable, ce qui est un plus. Après,Merise reste une méthode assez franco française je trouve, l'usage est donc limité, et ne justifie pas une mise à jour lourde. 
En tout cas merci, ça m'aide bien pour mes projets perso et la documentation qui va avec.

**Comment by laowantong** [comment]
Merci à vous !
