### ISSUE TITLE
--image_format svg have been removed from mocodo but not from mocodo_magic

### ISSUE THREAD

**Issue by vincentxavier** [laowantong/mocodo#63]
Using Mocodo magic in a Notebook fails with the mentionned message

**Comment by vincentxavier** [comment]
Actually, it's the mocodo_magic package that is not up to date. Maybe you should just upload a new version to Pypi.

**Comment by laowantong** [comment]
Could you please report this bug with enough details about your configuration, the steps needed to reproduce it and the expected results?

**Comment by vincentxavier** [comment]
I think it's really a mocodo_magic deprecation

If I remove mocodo_magic and choose `%load_ext mocodo`, everything works
fine.

-- 
Vincent-Xavier JUMEL Id: 0xBC8C2BAB14ABB3F2 https://blog.thetys-retz.net

Société Libre, Logiciel Libre http://www.april.org/adherer
Parinux, logiciel libre à Paris : http://www.parinux.org
