### ISSUE TITLE
DF à double sens : contrainte UNIQUE

### ISSUE THREAD

**Issue by laowantong** [laowantong/mocodo#82]
_Originally posted by @fduchatea in https://github.com/laowantong/mocodo/issues/79#issuecomment-1582463224_

Suite à une discussion avec les collègues, le cas d'une entité avec clé étrangère comme clé candidate est peu fréquent.
A-priori, c'est uniquement quand les cardinalités d'une asso sont 1,1 de chaque côté.

```
PERSONNES: id, nom
PE, 11 PERSONNES, 11 EMAILS
EMAILS : email, x, y
```

Dans ce cas, Mocodo devrait détecter que _email_ (ou _id_ selon la traduction) est une clé candidate (et donc lui assigner la représentation appropriée), et déclarer l'attribut en UNIQUE (+ NOT NULL) dans le code SQL.

S'il y a une cardinalité 0,1 alors ça ne fonctionne pas (on peut mettre la contrainte UNIQUE mais ce n'est pas forcément une clé puisque les NULL sont possibles).
S'il y a une cardinalité 0,n d'un côté, alors ça ne peut pas être une clé.

**Comment by laowantong** [comment]
C'est un genre d'association que j'interdis explicitement à mes étudiants. Mocodo le tolère, j'ai retrouvé ça dans la doc :

> Autre point litigieux: dans les dépendances fonctionnelles à double sens ((1,1) des deux côtés), la priorité est donnée à la première des entités énumérées dans l'association. Même chose quand deux (0,1) sont en concurrence.

Donc, ça donne de façon déterministe :

**EMAILS** (<ins>email</ins>, x, y)
**PERSONNES** (<ins>id</ins>, nom, _#email_)

Oui, Mocodo pourrait (devrait) alors ajouter les contraintes UNIQUE + NOT NULL sur l'attribut _email_.

**Comment by laowantong** [comment]
Je viens de traiter le sous-cas qui me paraît le plus intéressant, 01 --DF-- 11, par exemple :

![image](https://github.com/laowantong/mocodo/assets/3048819/0ada90e7-c03b-40e5-8b50-5dad52530177)

Ou, de façon plus complexe, avec des entités faibles et des contraintes d'unicité déjà données explicitement :

![image](https://github.com/laowantong/mocodo/assets/3048819/a18762f3-8951-4748-8e08-d8351b3aa5d8)

Cela fait suite à [cette discussion](https://www.developpez.net/forums/d2155258/general-developpement/alm/modelisation/schema/comparaison-mld/).

Je n'injecte toujours pas de contraintes NOT NULL pour le moment.

**Comment by laowantong** [comment]
Aperçu de la version 4, est-ce le résultat que vous attendiez ?

![image](https://github.com/laowantong/mocodo/assets/3048819/3ad7517e-93af-45ab-8e38-31018491980d)

**Comment by fduchatea** [comment]
C'est bien le résultat attendu.

Une remarque : en SQL, les attributs formant la clé primaire (id ou email, dans l'exemple précédent) sont désormais définis avec une contrainte NOT NULL (qui est évidemment inutile puisque la contrainte de clé primaire l'implique déjà).
Ca semble nouveau (j'utilise encore mocodo 3.2.0 et la contrainte NOT NULL n'apparait pas dans mes datasets).
Ce n'est pas vraiment gênant, mais j'imagine que ce serait mieux sans.

**Comment by laowantong** [comment]
Cool.

Concernant votre remarque, c'est un choix que j'ai fait après avoir lu quelques discussions sur ce sujet précis. Spécifier `NOT NULL` pour une clé primaire, quoique redondant, semble être généralement considéré comme une bonne pratique.
