### ISSUE TITLE
Error related to CairoSVG

### ISSUE THREAD

**Issue by PierreArragain** [laowantong/mocodo#85]
When I try to generate a diagram (including with the default example) I get this error : 
`Mocodo Err.13 - Générer un PNG ou un PDF requiert une installation fonctionnelle de
CairoSVG.`

**Comment by PierreArragain** [comment]
I used Mocodo Online without having anything to install before. Is it mandatory now ?

**Comment by laowantong** [comment]
No. However, describing a bug with enough details (e.g., that you used Mocodo Online) is recommended :wink:

**Comment by PierreArragain** [comment]
Yeah, I get the misunderstanding. So the error I got is on Mocodo Online (I actually did not know there was a local version of Mocodo, now I know 😉 ). Thanks for reopening the issue.

**Comment by laowantong** [comment]
Fixed. Thanks for raising this issue.
