### ISSUE TITLE
MCD illisible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [laowantong/mocodo#9]
```
Bonjour,

Je me permets moi aussi d'écrire en français pour soumettre un autre 
problème sous Ubuntu 12.04 en 64 bits.

L'exécution de la commande 
python mocodo.py

produit bien les fichiers attendus, mais le .svg produit et illisible (voir 
fichier joint).
Le résultat est le même pour des tests sur d'autres fichiers de définition 
de mcd.
Le problème n'était pas présent sur la version 1.4.1 du logiciel.

Je tiens à vous féliciter et à vous remercier de nous fournir un logiciel 
qui, malgré encore quelques problèmes, est je trouve de grande qualité, 
extrêmement pratique et bien documentée.
Je reste à votre disposition si besoin.

WaZaA
```

Original issue reported on code.google.com by `WaZa...@gmail.com` on 15 Jan 2013 at 9:05

Attachments:
* [sandbox.svg](https://storage.googleapis.com/google-code-attachments/mocodo/issue-9/comment-0/sandbox.svg)

**Comment by laowantong** [comment]
Désolé, je n'ai pris connaissance des bogues signalées sur Google Code qu'aujourd'hui en les retrouvant sur GitHub où je viens de faire migrer le projet. Le problème est normalement réglé dans la version 2 du logiciel.
