### ISSUE TITLE
MoCoDo.net v4 : documentation

### ISSUE THREAD

**Issue by Epithumia** [laowantong/mocodo#90]
Le lien vers la documentation sur le site web (https://rawgit.com/laowantong/mocodo/master/doc/fr_refman.html) et dans le README (https://github.com/laowantong/mocodo/blob/master/doc/fr_refman.html) ne sont plus valides.

**Comment by laowantong** [comment]
Oui, le fichier n'est plus là, désolé. Je finaliserai la nouvelle documentation dans la semaine.
