### ISSUE TITLE
Format des cardinalités relatives sous Mocodo online

### ISSUE THREAD

**Issue by Epithumia** [laowantong/mocodo#97]
les identifiants relatifs sont toujours "\_1,1\_" sur le site web, mais l'application permet depuis un certain temps (suite à ma demande !) de personnaliser ce qui est affiché : j'ai donc une première modification à proposer pour le site web pour ajouter une option (pour le moment, j'ai fait ça sous forme de liste de choix entre "\_1,1\_" (par défaut) et "1,1 (R)" comme Looping)

**Comment by laowantong** [comment]
(Effectivement deux issues / PR seraient préférables. Je réponds ici à la première. Si vous voulez en ouvrir une pour la seconde, merci de bien préciser si vous parlez de schéma relationnel (SR ?) ou de diagramme relationnel (visualisation avec des flèches) car je ne comprends pas trop ce qui vous intéresserait.)

1. Mocodo online est une vitrine, dont l'interface doit rester la plus simple possible. Je ne souhaite pas exposer l'ensemble des fonctionnalités et des options de la ligne de commande. Cependant, en l'occurrence, on devrait pouvoir caser l'option `--strengthen_card` dans les `details` (fermés par défaut) de « Découvrir… » au bout de la ligne :

    - [ ] Entité faible (ou identification relative) : [menu]

    Quitte à faire, il faudrait alors offrir les différentes conventions. Une recherche rapide fait apparaître :
    - `(1,1)` qui semble la plus répandue ;
    - `1,1 (R)` qui doit être la notation originelle. Dans _Merise 2e génération_ (Nanci et Espinasse), elle devient occasionnellement `(R) 1,1` :

    <img width="367" alt="image" src="https://github.com/laowantong/mocodo/assets/3048819/e3fdb4cd-5158-47e3-bebc-15e91b562631">

    - `1,1 Ⓡ` ;
    - `1,1` dans au moins [un cours](https://perso.liris.cnrs.fr/marc.plantevit/documents/C5ER.pdf), même si ça n'est pas suffisant dans certains cas ;
    - <ins>`1,1`</ins>, une idiosyncrasie de Mocodo , mais que je préfère à `1,1 (R)` pour sa légèreté, à `(1,1)` pour son caractère explicite, et qui me permet de parler de cardinalité « renforçante ».

**Comment by Epithumia** [comment]
> on devrait pouvoir caser l'option --strengthen_card dans les details (fermés par défaut) de « Découvrir… » au bout de la ligne :

Ca donne ça : 
![image](https://github.com/laowantong/mocodo/assets/893445/2e6d86ce-b49a-4e84-8d41-2a0a0411aceb)

Est-ce que ça ira ? C'est à mon avis un peu sale pour deux raisons : d'une part ça force à mettre du html dans une chaîne de caractère du fichier js, puis qu'une fois injecté par `createCheckboxes`, c'est de nouveau traité par le js pour injecter les options avec `createOptions` et que d'autre part ça fait une liste déroulante sans label associé, le texte "Entité faible (ou identification relative) " étant déjà label pour la checkbox.

Personnellement je l'aurais mis au même niveau de personnalisation que, et juste après, "Mise en forme des libellés pour SQL".

Pour le schéma/diagramme relationnel, ce dont je parle est de pouvoir sortir à partir du code suivant
```
:
TableA: idA, nomA
:
TableF: #idB > TableB > idB, _#idA > TableA > idA, attribut
:
TableB: idB, nomB
:
```
le diagramme : 
![image](https://github.com/laowantong/mocodo/assets/893445/587cfade-fb45-43d9-8aad-c95772de8efe)
au lieu de 
![image](https://github.com/laowantong/mocodo/assets/893445/9a8f6f9b-d9a5-4506-93de-ae48f991e269)
voire (soyons fous)
![image](https://github.com/laowantong/mocodo/assets/893445/c478ad5a-7891-477d-98c7-3b1b85b76140)

En faire une option sur le site web est secondaire (c'est un plus), mais sur l'application en ligne de commande, ça me serait vraiment utile de pouvoir faire les diagrammes sans #

**Comment by laowantong** [comment]
> Ca donne ça :

Non, le menu devrait être sur la même ligne.
 
> C'est à mon avis un peu sale pour deux raisons : d'une part ça force à mettre du html dans une chaîne de caractère du fichier js, puis qu'une fois injecté par `createCheckboxes`, c'est de nouveau traité par le js pour injecter les options avec `createOptions` et que d'autre part ça fait une liste déroulante sans label associé, le texte "Entité faible (ou identification relative) " étant déjà label pour la checkbox.

1. Peut-être créer le menu dans un `div` avec `display: none` et juste le déplacer et le rendre visible en JS ?
2. Ça ne me gêne pas. Vu mon niveau en web, un truc sale de plus ne fera pas de différence.

> Personnellement je l'aurais mis au même niveau de personnalisation que, et juste après, "Mise en forme des libellés pour SQL".

Pas moi, pour les raisons évoquées en introduction de ma réponse. Au contraire, si vous faites une PR, comme l'infrastructure sera en place, vous pouvez en profiter pour mettre le menu SQL au bout de la ligne "Requêtes SQL de création de table".

**Comment by Epithumia** [comment]
Une fois les deux PR pour les relatives et le croisillon finalisées, je ferai celle pour le choix web de croisillon (puisque ça va dépendre du nom de l'option et de si la méthode utilisée pour injecteur le menu est acceptée).
