### ISSUE TITLE
Masquer le croisillon # dans le diagramme relationnel

### ISSUE THREAD

**Issue by laowantong** [laowantong/mocodo#99]
- Jusqu'à Mocodo 3.x, il n'était pas requis de préfixer une clef étrangère par un croisillon, ce qui permettait de sortir des SR sans le symbole. Mocodo 4.x impose le croisillon en entrée, et de fait l'impose en sortie ; j'ai donc une modification de l'application prête qui ajoute une option pour personnaliser la *sortie* sans toucher à la syntaxe d'entrée ; j'ai fait en même temps un ajout pour le site web d'une option (pour le moment) en liste de choix avec "#" (par défaut) ou "" (chaîne vide, cela fait que les clés étrangères sont affichées comme des attributs normaux).

Pour le schéma/diagramme relationnel, ce dont je parle est de pouvoir sortir à partir du code suivant
```
:
TableA: idA, nomA
:
TableF: #idB > TableB > idB, _#idA > TableA > idA, attribut
:
TableB: idB, nomB
:
```
le diagramme : 
![image](https://github.com/laowantong/mocodo/assets/893445/587cfade-fb45-43d9-8aad-c95772de8efe)
au lieu de 
![image](https://github.com/laowantong/mocodo/assets/893445/9a8f6f9b-d9a5-4506-93de-ae48f991e269)
voire (soyons fous)
![image](https://github.com/laowantong/mocodo/assets/893445/c478ad5a-7891-477d-98c7-3b1b85b76140)

En faire une option sur le site web est secondaire (c'est un plus), mais sur l'application en ligne de commande, ça me serait vraiment utile de pouvoir faire les diagrammes sans #

_Originally posted by @Epithumia in https://github.com/laowantong/mocodo/issues/97#issuecomment-1786955175_

**Comment by laowantong** [comment]
@Epithumia
L'option sur le site web devrait également (#97) apparaître au bout de la ligne « Diagramme relationnel en Mocodo ». Je vais m'occuper du backend Python, je vous laisse la partie web.

**Comment by Epithumia** [comment]
Pour le backend python j'ai déjà aussi, je prépare les PR dans la journée.
